name: revanced_manager_flutter
description: 'A fun project, rebuilding the original ReVanced Manager using Flutter framework.'
publish_to: 'none'
version: 1.3.11+16

scripts:
  upgrade: 'flutter pub add dio intl yaml collection flutter_bloc url_launcher skeletonizer path_provider device_info_plus package_info_plus pretty_dio_logger shared_preferences cached_network_image && flutter pub add --dev flutter_lints'
  clean: 'flutter clean && flutter pub get'
  build: 'flutter build apk --release'
  rename: 'dart run lib/script.dart'
  open: 'open build/app/outputs/flutter-apk'
  prod: 'rps clean && rps build && rps rename && rps open'

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  intl: ^0.20.2
  yaml: ^3.1.3
  collection: ^1.19.1
  flutter_bloc: ^9.1.0
  url_launcher: ^6.3.1
  skeletonizer: ^1.4.3
  path_provider: ^2.1.5
  device_info_plus: ^11.3.3
  package_info_plus: ^8.3.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - android/app/src/main/ic_launcher-playstore.png

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400