name: revanced_manager_flutter
description: "A fun project, rebuilding the original ReVanced Manager using Flutter framework."
publish_to: 'none'
version: 1.2.0+3

scripts:
  clean: 'flutter clean && flutter pub get'
  build: 'flutter build apk --release'
  rename: 'dart run lib/script.dart'
  open: 'open build/app/outputs/flutter-apk'
  prod: 'rps clean && rps build && rps rename && rps open'

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  intl: ^0.20.1
  yaml: ^3.1.2
  flutter_bloc: ^8.1.6
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  installed_apps: ^1.5.2
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.1.1
  package_info_plus: ^8.1.2
  shared_preferences: ^2.3.3
  flutter_displaymode: ^0.6.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - android/app/src/main/ic_launcher-playstore.png

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Product-Sans-Regular.ttf
          weight: 400
