name: revanced_manager_flutter
description: 'A fun project, rebuilding the original RV Manager using Flutter framework.'
publish_to: 'none'
version: 2.1.1+27

scripts:
  clean: 'flutter clean && flutter pub get'
  build: 'flutter build apk --split-per-abi'
  rename: 'dart run lib/script/copy_rename_apk_file.dart'
  open: 'open build/app/outputs/flutter-apk'
  prod: 'rps clean && rps build && rps rename && rps open'

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  intl: ^0.20.2
  yaml: ^3.1.3
  collection: ^1.19.1
  flutter_bloc: ^9.1.1
  url_launcher: ^6.3.2
  skeletonizer: ^2.1.0+1
  path_provider: ^2.1.5
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - android/app/src/main/ic_launcher-playstore.png

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf